name: mxt
version: 1.8
author: MXT
main: me.mxt.mxtplugin.Main
softdepend: [ActionBarAPI, TitleAPI]
commands:
  mxt:
    description: main command of mxt plugin
  fly:
    description: Toggle fly
    usage: /<command>
  mxtreload:
    description: Reload the plugin
    usage: /<command>
  discord:
    description: Get discord link for this server (If you're admin then edit this in "mxt > config.yml" if you already didn't edit the link)
    usage: /<command>
  gms:
    description: Set your or other's gamemode to survival
    usage: /<command> [playername]
  gmc:
    description: Set your or other's gamemode to creative
    usage: /<command> [playername]
  gma:
    description: Set your or other's gamemode to adventure
    usage: /<command> [playername]
  gmsp:
    description: Set your or other's gamemode to spectator
    usage: /<command> [playername]
  heal:
    description: Set your or other's health to max
    usage: /<command> [playername]
  day:
    description: Set world time to day
    usage: /<command>
  night:
    description: Set world time to night
    usage: /<command>
  suicide:
    description: Kill yourself in-game
    usage: /<command>
  clean:
    description: Clear your inv
    usage: /<command>
  ping:
    description: Pong!
    usage: /<command>
  setspawn:
    description: Set spawn for your server
    usage: /<command>
  spawn:
    description: Teleport you or other's to spawn
    usage: /<command>
  flylist:
    description: Show the list of flying players
    usage: /<command>
  kickall:
    description: Kick everyone
    usage: /<command>
  safe:
    description: Turn on safe/maintenance mode
    usage: /<command>
  afk:
    description: Set someone or yourself to afk mode
    usage: /<command> [playername]
  msg:
    description: Send private message to a player
    usage: /<command> [playername] [message]
  invsee:
    description: See/edit someone's inventory
    usage: /<command> [playername]
  vanish:
    description: Toggle vanish
    usage: /<command>